In [3]:
# make a 2d array of size 29 by 29 to test
import numpy as np
from scipy import fft

array = np.array([[1]*29]*29)

array


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [4]:
# fourier transform like done in other files
dft = np.fft.fft2(array) # calculate QR code dft
dft

array([[ 8.41000000e+02+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
        -2.57571742e-14+0.j, -2.57571742e-14+0.j, -1.28785871e-14+0.j,
        -1.28785871e-14+0.j, -1.28785871e-14+0.j, -1.93178806e-14+0.j,
         0.00000000e+00+0.j, -1.28785871e-14+0.j, -1.28785871e-14+0.j,
        -1.28785871e-14+0.j, -9.65894031e-15+0.j, -9.65894031e-15+0.j,
        -9.65894031e-15+0.j, -9.65894031e-15+0.j, -1.28785871e-14+0.j,
        -1.28785871e-14+0.j, -1.28785871e-14+0.j,  0.00000000e+00+0.j,
        -1.93178806e-14+0.j, -1.28785871e-14+0.j, -1.28785871e-14+0.j,
        -1.28785871e-14+0.j, -2.57571742e-14+0.j, -2.57571742e-14+0.j,
         0.00000000e+00+0.j,  0.00000000e+00+0.j],
       [-2.84217094e-14+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
         0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
         0.00000000e+00+0.j,  0.00000000e+00+0.j,  7.88860905e-31+0.j,
         0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
         0.00000000e+00+0.

In [5]:
ift = fft.ifft(dft)

ift

array([[ 2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j,  2.90000000e+01+0.j,
         2.90000000e+01+0.j,  2.90000000e+01+0.j],
       [-9.80058946e-16+0.j, -9.80058946e-16+0.j, -9.80058946e-16+0.j,
        -9.80058946e-16+0.j, -9.80058946e-16+0.j, -9.80058946e-16+0.j,
        -9.80058946e-16+0.j, -9.80058946e-16+0.j, -9.80058946e-16+0.j,
        -9.80058946e-16+0.j, -9.80058946e-16+0.j, -9.80058946e-16+0.j,
        -9.80058946e-16+0.

In [1]:
# function to split DFT into real and imaginary parts and reshape them
def split_dft(dft_str):
    complex_numbers = [complex(c.strip()) for c in dft_str.strip('()').split(')(')]
    real_part = np.array([c.real for c in complex_numbers])
    imag_part = np.array([c.imag for c in complex_numbers])
    return real_part, imag_part

# apply the function to each row
df['dft_real'], df['dft_imag'] = zip(*df['dft'].apply(split_dft))

NameError: name 'df' is not defined